# IPF File Preparation for DGE and Downstream Analysis

In [1]:
# load required packages
library(data.table)
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()     masks data.table::between()
✖ dplyr::filter()      masks stats::filter()
✖ dplyr::first()       masks data.table::first()
✖ lubridate::hour()    masks data.table::hour()
✖ lubridate::isoweek() masks data.table::isoweek()
✖ dplyr::lag()         masks stats::lag()
✖ dplyr::last()        masks data.table::last()
✖ lubridate::mday()    masks data.table::mday()
✖ lubridate::minute()  masks data.table::minute()
✖ lubridate::month()   masks data.table::month()
✖ lubridate::quarter() masks data.table::quarter()
✖ lubridate::second()  masks data.table::second()
✖ purrr::transpose()   masks data.table::transpose()
✖ lubridate::wday()    masks data.table::wday()
✖ lubridate::week()    masks data.table::week()
✖ lubridate::yday()    masks data.table::yday()
✖ lubridate::year()    masks data.table::year()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
# read in data
counts <- fread("GSE213001_Entrez-IDs-Lung-IPF-GRCh38-p12-raw_counts.csv") #raw counts from GEO
meta <- fread("GSE213001_meta.txt", fill=TRUE) #series matrix file from GEO
emap <- fread("mart_export.txt", data.table=FALSE) #conversion between ensembl id and common gene symbol

In [3]:
head(meta)
head(counts)
head(emap)

  !Sample_title            ALF008C               ALF013B
1 !Sample_geo_accession    GSM6568317            GSM6568318
2 !Sample_status           Public on Nov 02 2022 Public on Nov 02 2022
3 !Sample_submission_date  Sep 09 2022           Sep 09 2022
4 !Sample_last_update_date Nov 02 2022           Nov 02 2022
5 !Sample_type             SRA                   SRA
6 !Sample_channel_count    1                     1
  ALF004C               ALF019A               ALF030A
1 GSM6568319            GSM6568320            GSM6568321
2 Public on Nov 02 2022 Public on Nov 02 2022 Public on Nov 02 2022
3 Sep 09 2022           Sep 09 2022           Sep 09 2022
4 Nov 02 2022           Nov 02 2022           Nov 02 2022
5 SRA                   SRA                   SRA
6 1                     1                     1
  ALF042C               ALF040B               ALF004D
1 GSM6568322            GSM6568323            GSM6568324
2 Public on Nov 02 2022 Public on Nov 02 2022 Public on Nov 02 2022
3 Sep 09 2022           Sep 09 2022           Sep 09 2022
4 Nov 02 2022           Nov 02 2022           Nov 02 2022
5 SRA                   SRA                   SRA
6 1                     1                     1
  ALF020A               ⋯ ALF023C               ALF033B
1 GSM6568325            ⋯ GSM6568446            GSM6568447
2 Public on Nov 02 2022 ⋯ Public on Nov 02 2022 Public on Nov 02 2022
3 Sep 09 2022           ⋯ Sep 09 2022           Sep 09 2022
4 Nov 02 2022           ⋯ Nov 02 2022           Nov 02 2022
5 SRA                   ⋯ SRA                   SRA
6 1                     ⋯ 1                     1
  ALF048A               ALF010A               ALF027B
1 GSM6568448            GSM6568449            GSM6568450
2 Public on Nov 02 2022 Public on Nov 02 2022 Public on Nov 02 2022
3 Sep 09 2022           Sep 09 2022           Sep 09 2022
4 Nov 02 2022           Nov 02 2022           Nov 02 2022
5 SRA                   SRA                   SRA
6 1                     1                     1
  ALF012B               ALF007D               ALF025C
1 GSM6568451            GSM6568452            GSM6568453
2 Public on Nov 02 2022 Public on Nov 02 2022 Public on Nov 02 2022
3 Sep 09 2022           Sep 09 2022           Sep 09 2022
4 Nov 02 2022           Nov 02 2022           Nov 02 2022
5 SRA                   SRA                   SRA
6 1                     1                     1
  ALF042A               ALF032C
1 GSM6568454            GSM6568455
2 Public on Nov 02 2022 Public on Nov 02 2022
3 Sep 09 2022           Sep 09 2022
4 Nov 02 2022           Nov 02 2022
5 SRA                   SRA
6 1                     1

  V1              ALF001 ALF004C ALF004D ALF007A ALF007B ALF007C ALF007D
1 ENSG00000279457  21     39      62      42      32      28      17
2 ENSG00000187634 287    379     383     313     188     402     158
3 ENSG00000188976 484    679     769     727     627     686     685
4 ENSG00000187961  66    228     230     198     113     181      75
5 ENSG00000187583  18     47      65      25      23      35      11
6 ENSG00000188290 142    173     216     181     168     179     264
  ALF008A ALF008B ⋯ ALF048A ALF048B ALF048C ALF048D ALF049A ALF049B ALF050A
1  21      27     ⋯  40      36      45      36      27      41      57
2 413     777     ⋯  71      46      33     253      60     111      42
3 610     629     ⋯ 602     529     638     668     766     758     671
4 156     186     ⋯  98     138     147      87     142     152     237
5  68      35     ⋯  19      31      30      11      17       9      24
6 106     250     ⋯ 143     194     150     206     180     121     224
  ALF050B ALF050C ALF050D
1  52      57      49
2  18      23      28
3 703     766     703
4 183     264     195
5  25      18      22
6 139     140      94

  Gene stable ID  Gene name Transcript stable ID
1 ENSG00000210049 MT-TF     ENST00000387314
2 ENSG00000211459 MT-RNR1   ENST00000389680
3 ENSG00000210077 MT-TV     ENST00000387342
4 ENSG00000210082 MT-RNR2   ENST00000387347
5 ENSG00000209082 MT-TL1    ENST00000386347
6 ENSG00000198888 MT-ND1    ENST00000361390

In [4]:
geneIDs <- counts$V1
counts$V1 <- NULL
counts <- as.matrix(counts)
rownames(counts) <- geneIDs

In [5]:
# counts: your matrix (genes x cells), rownames = Ensembl IDs
# emap: data.frame with columns 'gene' (Ensembl) and 'symbol'
is.numeric(counts)

# 1. Match Ensembl IDs to symbols
symbols <- emap$`Gene name`[match(rownames(counts), emap$`Gene stable ID`)]

# Optional: handle missing mappings
symbols[is.na(symbols)] <- rownames(counts)[is.na(symbols)]  # or drop them

# 2. Aggregate rows by symbol
counts_agg <- rowsum(counts, group = symbols)

# Done: rownames(counts_agg) are gene symbols
head(counts_agg)

[1] TRUE

       ALF001 ALF004C ALF004D ALF007A ALF007B ALF007C ALF007D ALF008A ALF008B
         3550  1850    3096     2718    8412    9887   3258     3305    1558
A2M    165871 80249   75169   181382  170068  142520  50222   162937  201332
A4GALT    520   314     402      461     707     549    605      349     420
AAAS      340   575     709      556     495     615    304      445     529
AACS      181   400     493      232     345     218    622      231     279
AADAC      51    47      61       36      74      20    569       49      54
       ALF008C ⋯ ALF048A ALF048B ALF048C ALF048D ALF049A ALF049B ALF050A
         1403  ⋯  2194    2959    2055    1767     1775    2440   1463
A2M    195201  ⋯ 55966   66348   54162   43246   121380  118318  98106
A4GALT    530  ⋯   198     216     325     407      399     263    275
AAAS      512  ⋯   320     380     426     216      499     671    505
AACS      333  ⋯   244     235     253     438      293     372    406
AADAC       9  ⋯    50       9      36     233       25      87     36
       ALF050B ALF050C ALF050D
        1396    1772    1531
A2M    83022   87190   97983
A4GALT   250     251     240
AAAS     500     578     515
AACS     370     391     371
AADAC     42      26      26

In [6]:
dim(counts_agg)
dim(counts)

[1] 15027   139

[1] 15065   139

In [8]:
# data contains IPF (disease) NDC (control) and some other conditions. check sample length for each
meta$`!Sample_title`
meta$ALF008C
sampledeets <- as.vector(t(meta[7]))
diseasegroup <- as.vector(t(meta[17]))
IPF <- c('diseasegroup: IPF', 'Lung,IPF.Apex,Whole lung', 'Lung,IPF.Base,Whole lung', 'Lung,IPF.NA,Whole lung')
ILD <- c('diseasegroup: ILD', 'Lung,ILD.Apex,Whole lung', 'Lung,ILD.Base,Whole lung')
NDC <- c('diseasegroup: NDC', 'Lung,NDC.Base,Whole lung', 'Lung,NDC.Apex,Whole lung', 'Lung,NDC.NA,Whole lung')
CLAD <- c('diseasegroup: CLAD', 'Lung,CLAD.Apex,Whole lung', 'Lung,CLAD.Base,Whole lung')

length(sampledeets[sampledeets %in% IPF == TRUE])
length(sampledeets[sampledeets %in% ILD == TRUE])
length(sampledeets[sampledeets %in% NDC == TRUE])
length(sampledeets[sampledeets %in% CLAD == TRUE])

 [1] "!Sample_geo_accession"           "!Sample_status"
 [3] "!Sample_submission_date"         "!Sample_last_update_date"
 [5] "!Sample_type"                    "!Sample_channel_count"
 [7] "!Sample_source_name_ch1"         "!Sample_organism_ch1"
 [9] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[11] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[13] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[15] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[17] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[19] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[21] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[23] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[25] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[27] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[29] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[31] "!Sample_characteristics_ch1"     "!Sample_characteristics_ch1"
[33] "!Sample_characteristics_ch1"     "!Sample_molecule_ch1"
[35] "!Sample_extract_protocol_ch1"    "!Sample_extract_protocol_ch1"
[37] "!Sample_taxid_ch1"               "!Sample_data_processing"
[39] "!Sample_data_processing"         "!Sample_data_processing"
[41] "!Sample_platform_id"             "!Sample_contact_name"
[43] "!Sample_contact_email"           "!Sample_contact_department"
[45] "!Sample_contact_institute"       "!Sample_contact_address"
[47] "!Sample_contact_city"            "!Sample_contact_state"
[49] "!Sample_contact_zip/postal_code" "!Sample_contact_country"
[51] "!Sample_data_row_count"          "!Sample_instrument_model"
[53] "!Sample_library_selection"       "!Sample_library_source"
[55] "!Sample_library_strategy"        "!Sample_relation"
[57] "!Sample_supplementary_file_1"    "!series_matrix_table_begin"
[59] "ID_REF"                          "!series_matrix_table_end"

 [1] "GSM6568317"
 [2] "Public on Nov 02 2022"
 [3] "Sep 09 2022"
 [4] "Nov 02 2022"
 [5] "SRA"
 [6] "1"
 [7] "Lung,IPF.Apex,Whole lung"
 [8] "Homo sapiens"
 [9] "tissue: Whole lung"
[10] "donorid: ALF008"
[11] "group: IPF.Apex"
[12] "lib.size: 15573259"
[13] "norm.factors: 1.00856304467136"
[14] "lunglocation: Apex"
[15] "leftright: Right"
[16] "diseasenormal: Disease"
[17] "diseasegroup: IPF"
[18] "gender: M"
[19] "diagnosis: IPF"
[20] "age: 65"
[21] "lungweight mg: 22"
[22] "rnaconcentration ngul: 201"
[23] "rin: 7.7"
[24] "volum ul: 14"
[25] "processingdate: 5/1/2018"
[26] "diseasesubtype: IPF"
[27] "smokingstatus: Ex-Smoker"
[28] "severity: Severe"
[29] "fvcprebd perc: 43"
[30] "dlco perc: 36"
[31] "dlco perc_corrected: NA"
[32] "diseasegroup1: IPF"
[33] "age group: Senior Adult (>=60)"
[34] "polyA RNA"
[35] "RNA was extracted from whole lung tissue according to manufacturer’s protocol (Fibrous Tissue Mini kit, Qiagen #74704). RNA quality was verified with the Agilent 2100 Bioanalyzer platform (Agilent Technologies). Samples with RNA integrity numbers (RIN) over 6 were used for RNA sequencing."
[36] "cDNA libraries were prepared for sequencing using standard strand specific TrueSeq kits with ribosomal RNA and Globin mRNA depletion. At least 20 million 100 bp single-end reads were generated per sample using Illumina HiSeq 3000 (Illumina, California, USA) using standard protocols at the Australian Genome Research Facility (AGRF, Melbourne, Australia)."
[37] "9606"
[38] "Image analysis was performed in real time by the HiSeq Control Software (HCS) v2.2.68 and Real Time Analysis (RTA) v1.18.66.3, running on the instrument computer. RTA performs real-time base calling on the HiSeq instrument computer. Then the Illumina bcl2fastq 2.20.0.422 pipeline was used to generate the sequence data."
[39] "Sequenced reads were mapped to human reference genome GRCh38.p12 using star (v2.6.1)13 with default parameters except for the --quantMode TranscriptomeSAM setting."
[40] "Reads were summarized at the gene level using featureCounts tool from the Subread package (v1.6.4)14, in a strand-specific manner."
[41] "GPL21290"
[42] "Katherine,,Monaghan"
[43] "katherine.monaghan@csl.com.au"
[44] "Research and Development"
[45] "CSL Limited"
[46] "30 Flemington Rd, Parkville"
[47] "Melbourne"
[48] "Victoria"
[49] "3052"
[50] "Australia"
[51] "0"
[52] "Illumina HiSeq 3000"
[53] "cDNA"
[54] "transcriptomic"
[55] "RNA-Seq"
[56] "BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN30751117"
[57] "NONE"
[58] ""
[59] "GSM6568317"
[60] ""

[1] 62

[1] 26

[1] 41

[1] 10

In [9]:
dim(meta)

IPFmeta <- meta[, sampledeets %in% IPF]
NDCmeta <- meta[, sampledeets %in% NDC]

meta <- meta[7:34]
idx <- meta[[1]] == '!Sample_characteristics_ch1'

vals <- meta[[2]][idx]
newNames <- trimws(sub(":.*", "", vals)) #adjust metadata row/column names to be more descriptive
meta[[1]][idx] <- newNames

meta

[1]  60 140

   !Sample_title           ALF008C
1  !Sample_source_name_ch1 Lung,IPF.Apex,Whole lung
2  !Sample_organism_ch1    Homo sapiens
3  tissue                  tissue: Whole lung
4  donorid                 donorid: ALF008
5  group                   group: IPF.Apex
6  lib.size                lib.size: 15573259
7  norm.factors            norm.factors: 1.00856304467136
8  lunglocation            lunglocation: Apex
9  leftright               leftright: Right
10 diseasenormal           diseasenormal: Disease
11 diseasegroup            diseasegroup: IPF
12 gender                  gender: M
13 diagnosis               diagnosis: IPF
14 age                     age: 65
15 lungweight mg           lungweight mg: 22
16 rnaconcentration ngul   rnaconcentration ngul: 201
17 rin                     rin: 7.7
18 volum ul                volum ul: 14
19 processingdate          processingdate: 5/1/2018
20 diseasesubtype          diseasesubtype: IPF
21 smokingstatus           smokingstatus: Ex-Smoker
22 severity                severity: Severe
23 fvcprebd perc           fvcprebd perc: 43
24 dlco perc               dlco perc: 36
25 dlco perc_corrected     dlco perc_corrected: NA
26 diseasegroup1           diseasegroup1: IPF
27 age group               age group: Senior Adult (>=60)
28 !Sample_molecule_ch1    polyA RNA
   ALF013B                        ALF004C
1  Lung,NDC.Base,Whole lung       Lung,ILD.Apex,Whole lung
2  Homo sapiens                   Homo sapiens
3  tissue: Whole lung             tissue: Whole lung
4  donorid: ALF013                donorid: ALF004
5  group: NDC.Base                group: ILD.Apex
6  lib.size: 14146498             lib.size: 12253541
7  norm.factors: 1.02594520742844 norm.factors: 0.978385212501405
8  lunglocation: Base             lunglocation: Apex
9  leftright: Unclassified        leftright: Left
10 diseasenormal: Normal          diseasenormal: Disease
11 diseasegroup: NDC              diseasegroup: ILD
12 gender: F                      gender: M
13 diagnosis: NDC                 diagnosis: ILD
14 age: 28                        age: 45
15 lungweight mg: 24              lungweight mg: 24
16 rnaconcentration ngul: 1027    rnaconcentration ngul: 556
17 rin: 7.7                       rin: 6
18 volum ul: 14                   volum ul: 14
19 processingdate: 5/1/2018       processingdate: 5/1/2018
20 diseasesubtype: NDC            diseasesubtype: NSIP
21 smokingstatus: Ex-Smoker       smokingstatus: Ex-Smoker
22 severity: Unknown              severity: Severe
23 fvcprebd perc: NA              fvcprebd perc: 38
24 dlco perc: NA                  dlco perc: NA
25 dlco perc_corrected: NA        dlco perc_corrected: NA
26 diseasegroup1: NDC             diseasegroup1: ILD
27 age group: Adult [19-59]       age group: Adult [19-59]
28 polyA RNA                      polyA RNA
   ALF019A                         ALF030A
1  Lung,IPF.Apex,Whole lung        Lung,NDC.Apex,Whole lung
2  Homo sapiens                    Homo sapiens
3  tissue: Whole lung              tissue: Whole lung
4  donorid: ALF019                 donorid: ALF030
5  group: IPF.Apex                 group: NDC.Apex
6  lib.size: 11850218              lib.size: 11836796
7  norm.factors: 0.985785966310314 norm.factors: 0.992227170953119
8  lunglocation: Apex              lunglocation: Apex
9  leftright: Left                 leftright: Left
10 diseasenormal: Disease          diseasenormal: Normal
11 diseasegroup: IPF               diseasegroup: NDC
12 gender: F                       gender: F
13 diagnosis: IPF                  diagnosis: NDC
14 age: 56                         age: 35
15 lungweight mg: 30               lungweight mg: 27
16 rnaconcentration ngul: 527      rnaconcentration ngul: 356
17 rin: 7.1                        rin: 8.9
18 volum ul: 14                    volum ul: 14
19 processingdate: 5/1/2018        processingdate: 5/2/2018
20 diseasesubtype: IPF             diseasesubtype: NDC
21 smokingstatus: Never            smokingstatus: Unknown
22 severity: Advanced              severity: Unknown
23 fvcprebd perc: 47               fvcprebd perc: NA
24 dlco perc: 16                   dlco perc: NA
25 dlco perc_corrected: NA         dlco perc_corrected: NA
26 diseasegroup1: IPF              diseasegroup1: NDC
27 age group: Adult [19-59]        age group: Adult [19-59]
28 polyA RNA                       polyA RNA
   ALF042C                        ALF040B
1  Lung,ILD.Apex,Whole lung       Lung,IPF.Base,Whole lung
2  Homo sapiens                   Homo sapiens
3  tissue: Whole lung             tissue: Whole lung
4  donorid: ALF042                donorid: ALF040
5  group: ILD.Apex                group: IPF.Base
6  lib.size: 13033300             lib.size: 13232206
7  norm.factors: 0.99321707994247 norm.factors: 1.14453734264326
8  lunglocation: Apex             lunglocation: Base
9  leftright: Right               leftright: Right
10 diseasenormal: Disease         diseasenormal: Disease
11 diseasegroup: ILD              diseasegroup: IPF
12 gender: F                      gender: F
13 diagnosis: ILD                 diagnosis: IPF
14 age: 61                        age: 71
15 lungweight mg: 42              lungweight mg: 22
16 rnaconcentration ngul: 218     rnaconcentration ngul: 490
17 rin: 7                         rin: 8.7
18 volum ul: 14                   volum ul: 14
19 processingdate: 5/8/2018       processingdate: 5/8/2018
20 diseasesubtype: IPF            diseasesubtype: IPF
21 smokingstatus: Never           smokingstatus: Never
22 severity: Advanced             severity: Severe
23 fvcprebd perc: 39              fvcprebd perc: 39
24 dlco perc: 28                  dlco perc: NA
25 dlco perc_corrected: 28        dlco perc_corrected: NA
26 diseasegroup1: ILD             diseasegroup1: IPF
27 age group: Senior Adult (>=60) age group: Senior Adult (>=60)
28 polyA RNA                      polyA RNA
   ALF004D                        ALF020A                         ⋯
1  Lung,ILD.Base,Whole lung       Lung,NDC.Apex,Whole lung        ⋯
2  Homo sapiens                   Homo sapiens                    ⋯
3  tissue: Whole lung             tissue: Whole lung              ⋯
4  donorid: ALF004                donorid: ALF020                 ⋯
5  group: ILD.Base                group: NDC.Apex                 ⋯
6  lib.size: 12033084             lib.size: 13188455              ⋯
7  norm.factors: 1.02693976721045 norm.factors: 0.987156782113402 ⋯
8  lunglocation: Base             lunglocation: Apex              ⋯
9  leftright: Left                leftright: Right                ⋯
10 diseasenormal: Disease         diseasenormal: Normal           ⋯
11 diseasegroup: ILD              diseasegroup: NDC               ⋯
12 gender: M                      gender: M                       ⋯
13 diagnosis: ILD                 diagnosis: NDC                  ⋯
14 age: 45                        age: 41                         ⋯
15 lungweight mg: 35              lungweight mg: 25               ⋯
16 rnaconcentration ngul: 1080    rnaconcentration ngul: 201      ⋯
17 rin: 6.1                       rin: 8.7                        ⋯
18 volum ul: 14                   volum ul: 14                    ⋯
19 processingdate: 5/1/2018       processingdate: 5/2/2018        ⋯
20 diseasesubtype: NSIP           diseasesubtype: NDC             ⋯
21 smokingstatus: Ex-Smoker       smokingstatus: Ex-Smoker        ⋯
22 severity: Severe               severity: Unknown               ⋯
23 fvcprebd perc: 38              fvcprebd perc: NA               ⋯
24 dlco perc: NA                  dlco perc: NA                   ⋯
25 dlco perc_corrected: NA        dlco perc_corrected: NA         ⋯
26 diseasegroup1: ILD             diseasegroup1: NDC              ⋯
27 age group: Adult [19-59]       age group: Adult [19-59]        ⋯
28 polyA RNA                      polyA RNA                       ⋯
   ALF023C                         ALF033B
1  Lung,IPF.Apex,Whole lung        Lung,CLAD.Base,Whole lung
2  Homo sapiens                    Homo sapiens
3  tissue: Whole lung              tissue: Whole lung
4  donorid: ALF023                 donorid: ALF033
5  group: IPF.Apex                 group: CLAD.Base
6  lib.size: 11812437              lib.size: 12348283
7  norm.factors: 0.988917073252069 norm.factors: 1.14114597200271
8  lunglocation: Apex              lunglocation: Base
9  leftright: Right                leftright: Unclassified
10 diseasenormal: Disease          diseasenormal: Disease
11 diseasegroup: IPF               diseasegroup: CLAD
12 gender: M                       gender: M
13 diagnosis: IPF                  diagnosis: CLAD
14 age: 61                         age: 69
15 lungweight mg: 35               lungweight mg: 27
16 rnaconcentration ngul: 490      rnaconcentration ngul: 825
17 rin: 8                          rin: 7.3
18 volum ul: 14                    volum ul: 14
19 processingdate: 5/2/2018        processingdate: 5/8/2018
20 diseasesubtype: IPF             diseasesubtype: CPFE
21 smokingstatus: Never            smokingstatus: Ex-Smoker
22 severity: Advanced              severity: Severe
23 fvcprebd perc: 43               fvcprebd perc: 63
24 dlco perc: 17                   dlco perc: 22
25 dlco perc_corrected: 17         dlco perc_corrected: 22
26 diseasegroup1: IPF              diseasegroup1: CLAD
27 age group: Senior Adult (>=60)  age group: Senior Adult (>=60)
28 polyA RNA                       polyA RNA
   ALF048A                         ALF010A
1  Lung,CLAD.Apex,Whole lung       Lung,NDC.Apex,Whole lung
2  Homo sapiens                    Homo sapiens
3  tissue: Whole lung              tissue: Whole lung
4  donorid: ALF048                 donorid: ALF010
5  group: CLAD.Apex                group: NDC.Apex
6  lib.size: 12753900              lib.size: 12276425
7  norm.factors: 0.892434169046925 norm.factors: 0.885049569435388
8  lunglocation: Apex              lunglocation: Apex
9  leftright: Right                leftright: Right
10 diseasenormal: Disease          diseasenormal: Normal
11 diseasegroup: CLAD              diseasegroup: NDC
12 gender: F                       gender: M
13 diagnosis: CLAD                 diagnosis: NDC
14 age: 49                         age: 69
15 lungweight mg: 20               lungweight mg: 40
16 rnaconcentration ngul: 174      rnaconcentration ngul: 331
17 rin: 7.2                        rin: 4.1
18 volum ul: 14                    volum ul: 14
19 processingdate: 5/8/2018        processingdate: 5/1/2018
20 diseasesubtype: CLAD            diseasesubtype: NDC
21 smokingstatus: Ex-Smoker        smokingstatus: Ex-Smoker
22 severity: Severe                severity: Unknown
23 fvcprebd perc: 35               fvcprebd perc: NA
24 dlco perc: NA                   dlco perc: NA
25 dlco perc_corrected: NA         dlco perc_corrected: NA
26 diseasegroup1: CLAD             diseasegroup1: NDC
27 age group: Adult [19-59]        age group: Senior Adult (>=60)
28 polyA RNA                       polyA RNA
   ALF027B                        ALF012B
1  Lung,IPF.Base,Whole lung       Lung,NDC.Base,Whole lung
2  Homo sapiens                   Homo sapiens
3  tissue: Whole lung             tissue: Whole lung
4  donorid: ALF027                donorid: ALF012
5  group: IPF.Base                group: NDC.Base
6  lib.size: 11558345             lib.size: 13007118
7  norm.factors: 1.08873416705084 norm.factors: 0.882478583100834
8  lunglocation: Base             lunglocation: Base
9  leftright: Left                leftright: Right
10 diseasenormal: Disease         diseasenormal: Normal
11 diseasegroup: IPF              diseasegroup: NDC
12 gender: M                      gender: F
13 diagnosis: IPF                 diagnosis: NDC
14 age: 57                        age: 60
15 lungweight mg: 40              lungweight mg: 28
16 rnaconcentration ngul: 660     rnaconcentration ngul: 1077
17 rin: 6.3                       rin: 4.4
18 volum ul: 14                   volum ul: 14
19 processingdate: 5/2/2018       processingdate: 5/1/2018
20 diseasesubtype: IPF            diseasesubtype: NDC
21 smokingstatus: Ex-Smoker       smokingstatus: Current
22 severity: Advanced             severity: Unknown
23 fvcprebd perc: 42              fvcprebd perc: NA
24 dlco perc: 13                  dlco perc: NA
25 dlco perc_corrected: 13        dlco perc_corrected: NA
26 diseasegroup1: IPF             diseasegroup1: NDC
27 age group: Adult [19-59]       age group: Senior Adult (>=60)
28 polyA RNA                      polyA RNA
   ALF007D                         ALF025C
1  Lung,ILD.Base,Whole lung        Lung,NDC.Apex,Whole lung
2  Homo sapiens                    Homo sapiens
3  tissue: Whole lung              tissue: Whole lung
4  donorid: ALF007                 donorid: ALF025
5  group: ILD.Base                 group: NDC.Apex
6  lib.size: 12503837              lib.size: 12017777
7  norm.factors: 0.782919731362293 norm.factors: 1.04088750770238
8  lunglocation: Base              lunglocation: Apex
9  leftright: Right                leftright: Left
10 diseasenormal: Disease          diseasenormal: Normal
11 diseasegroup: ILD               diseasegroup: NDC
12 gender: F                       gender: M
13 diagnosis: ILD                  diagnosis: NDC
14 age: 65                         age: 45
15 lungweight mg: 38               lungweight mg: 42
16 rnaconcentration ngul: 161      rnaconcentration ngul: 391
17 rin: 6.8                        rin: 6.9
18 volum ul: 14                    volum ul: 14
19 processingdate: 5/1/2018        processingdate: 5/2/2018
20 diseasesubtype: CTD-ILD         diseasesubtype: NDC
21 smokingstatus: Ex-Smoker        smokingstatus: Unknown
22 severity: Advanced              severity: Unknown
23 fvcprebd perc: 39               fvcprebd perc: NA
24 dlco perc: 19                   dlco perc: NA
25 dlco perc_corrected: 17         dlco perc_corrected: NA
26 diseasegroup1: ILD              diseasegroup1: NDC
27 age group: Senior Adult (>=60)  age group: Adult [19-59]
28 polyA RNA                       polyA RNA
   ALF042A                        ALF032C
1  Lung,ILD.Apex,Whole lung       Lung,IPF.Apex,Whole lung
2  Homo sapiens                   Homo sapiens
3  tissue: Whole lung             tissue: Whole lung
4  donorid: ALF042                donorid: ALF032
5  group: ILD.Apex                group: IPF.Apex
6  lib.size: 11212973             lib.size: 11266154
7  norm.factors: 1.00125709880949 norm.factors: 1.09009337597802
8  lunglocation: Apex             lunglocation: Apex
9  leftright: Left                leftright: Right
10 diseasenormal: Disease         diseasenormal: Disease
11 diseasegroup: ILD              diseasegroup: IPF
12 gender: F                      gender: M
13 diagnosis: ILD                 diagnosis: IPF
14 age: 61                        age: 54
15 lungweight mg: 36              lungweight mg: 16
16 rnaconcentration ngul: 693     rnaconcentration ngul: 188
17 rin: 6.3                       rin: 7.3
18 volum ul: 14                   volum ul: 14
19 processingdate: 5/8/2018       processingdate: 5/2/2018
20 diseasesubtype: IPF            diseasesubtype: IPF
21 smokingstatus: Never           smokingstatus: Ex-Smoker
22 severity: Advanced             severity: Advanced
23 fvcprebd perc: 39              fvcprebd perc: 0.92
24 dlco perc: 28                  dlco perc: 0.31
25 dlco perc_corrected: 28        dlco perc_corrected: 0.29
26 diseasegroup1: ILD             diseasegroup1: IPF
27 age group: Senior Adult (>=60) age group: Adult [19-59]
28 polyA RNA                      polyA RNA

In [10]:
rownames(meta) <- meta[[1]]
metaclean <- meta[, -1]

meta[idx, (colnames(meta)) := lapply(.SD, function(x) {
  trimws(sub("^[^:]+:\\s*", "", as.character(x)))
})]

In [11]:
metaclean <- t(meta)
colnames(metaclean) <- as.character(metaclean[1, ])
metaclean <- metaclean[-1, ]
head(metaclean)

        !Sample_source_name_ch1  !Sample_organism_ch1 tissue     donorid
ALF008C Lung,IPF.Apex,Whole lung Homo sapiens         Whole lung ALF008
ALF013B Lung,NDC.Base,Whole lung Homo sapiens         Whole lung ALF013
ALF004C Lung,ILD.Apex,Whole lung Homo sapiens         Whole lung ALF004
ALF019A Lung,IPF.Apex,Whole lung Homo sapiens         Whole lung ALF019
ALF030A Lung,NDC.Apex,Whole lung Homo sapiens         Whole lung ALF030
ALF042C Lung,ILD.Apex,Whole lung Homo sapiens         Whole lung ALF042
        group    lib.size norm.factors      lunglocation leftright
ALF008C IPF.Apex 15573259 1.00856304467136  Apex         Right
ALF013B NDC.Base 14146498 1.02594520742844  Base         Unclassified
ALF004C ILD.Apex 12253541 0.978385212501405 Apex         Left
ALF019A IPF.Apex 11850218 0.985785966310314 Apex         Left
ALF030A NDC.Apex 11836796 0.992227170953119 Apex         Left
ALF042C ILD.Apex 13033300 0.99321707994247  Apex         Right
        diseasenormal ⋯ processingdate diseasesubtype smokingstatus severity
ALF008C Disease       ⋯ 5/1/2018       IPF            Ex-Smoker     Severe
ALF013B Normal        ⋯ 5/1/2018       NDC            Ex-Smoker     Unknown
ALF004C Disease       ⋯ 5/1/2018       NSIP           Ex-Smoker     Severe
ALF019A Disease       ⋯ 5/1/2018       IPF            Never         Advanced
ALF030A Normal        ⋯ 5/2/2018       NDC            Unknown       Unknown
ALF042C Disease       ⋯ 5/8/2018       IPF            Never         Advanced
        fvcprebd perc dlco perc dlco perc_corrected diseasegroup1
ALF008C 43            36        NA                  IPF
ALF013B NA            NA        NA                  NDC
ALF004C 38            NA        NA                  ILD
ALF019A 47            16        NA                  IPF
ALF030A NA            NA        NA                  NDC
ALF042C 39            28        28                  ILD
        age group           !Sample_molecule_ch1
ALF008C Senior Adult (>=60) polyA RNA
ALF013B Adult [19-59]       polyA RNA
ALF004C Adult [19-59]       polyA RNA
ALF019A Adult [19-59]       polyA RNA
ALF030A Adult [19-59]       polyA RNA
ALF042C Senior Adult (>=60) polyA RNA

In [12]:
colnames(metaclean)
metaclean <- as.data.frame(metaclean)
head(metaclean$diseasegroup)

metaclean <- filter(metaclean, metaclean$diseasegroup %in% c("IPF", "NDC"))
unique(metaclean$diseasegroup)
dim(metaclean)

 [1] "!Sample_source_name_ch1" "!Sample_organism_ch1"
 [3] "tissue"                  "donorid"
 [5] "group"                   "lib.size"
 [7] "norm.factors"            "lunglocation"
 [9] "leftright"               "diseasenormal"
[11] "diseasegroup"            "gender"
[13] "diagnosis"               "age"
[15] "lungweight mg"           "rnaconcentration ngul"
[17] "rin"                     "volum ul"
[19] "processingdate"          "diseasesubtype"
[21] "smokingstatus"           "severity"
[23] "fvcprebd perc"           "dlco perc"
[25] "dlco perc_corrected"     "diseasegroup1"
[27] "age group"               "!Sample_molecule_ch1"

[1] "IPF" "NDC" "ILD" "IPF" "NDC" "ILD"

[1] "IPF" "NDC"

[1] 103  28

In [13]:
all(rownames(metaclean) %in% colnames(counts))
counts <- as.data.frame(counts)

counts <- counts %>% select(rownames(metaclean))
counts

[1] TRUE

                ALF008C ALF013B ALF019A ALF030A ALF040B ALF020A ALF047A ALF029A
ENSG00000279457   29      31      43      49      26      20      53      34
ENSG00000187634  846     168     241      46     211     108     270     281
ENSG00000188976  774    1168     568     565     813     590     747     655
ENSG00000187961  154     211     112     103     142     118     156     170
ENSG00000187583   63      42      19      11      41      26      25      34
ENSG00000188290  197     115     196      81     156     172     181     172
ENSG00000187608  480     299     337     172     118     361     319     595
ENSG00000188157 2155    1016    1767    1735    2263    2396    2196    3019
ENSG00000131591  198     156     140     155     203     158     218     173
ENSG00000162571    5      90      11      10     610      13      38      13
ENSG00000186891   52      28      16       6      77      10      66      51
ENSG00000186827   80      42      74      27      71      76     185     114
ENSG00000078808 2272    1940    1706    1582    1595    2004    2210    1854
ENSG00000176022  308     443     259     244     253     277     260     285
ENSG00000184163    6       6      10      16       4       5      12       7
ENSG00000160087  668     684     403     421     494     453     487     543
ENSG00000162572  126      34      88      78      90      82     153      95
ENSG00000131584 1432     643     770     650     771     795    1024     922
ENSG00000169972  142     142      74     104     122      98     100      78
ENSG00000127054 1022    1106     810     813    1114     942    1112     951
ENSG00000224051  269     305     222     208     236     257     262     271
ENSG00000169962   15       5       9      10      66       9      39      23
ENSG00000107404  879     886     557     774     610     708     723     657
ENSG00000162576 3733    1024    2480     770     897    1662    2655    2540
ENSG00000175756  545     836     381     491     495     483     460     415
ENSG00000221978 3510    2477    2742    2690    3275    2878    3171    3200
ENSG00000242485  647     882     462     549     588     621     567     591
ENSG00000235098  214     233     110     165     823     312     166     174
ENSG00000179403  901     980    1072     369     968     977     679     735
ENSG00000215915   88     156      61      83      92     137      69      66
⋮               ⋮       ⋮       ⋮       ⋮       ⋮       ⋮       ⋮       ⋮
ENSG00000067646    342       0       1       0       0     180     184     215
ENSG00000114374    967       0       0       0       0     709     703     815
ENSG00000067048   1815       0       0       0       0    1016    1450    1249
ENSG00000183878    376       0       0       0       0     367     354     340
ENSG00000165246    213       0       0       0       0      69     113     127
ENSG00000012817   1367       1       1       0       1    1567    1438    1590
ENSG00000198692    280       1       0       0       0     263     242     240
ENSG00000198888  54772   41381   26456   35895   32641   40950   59549   31262
ENSG00000198763  46626   44290   42827   40796   42466   47040   58536   30594
ENSG00000198804 246974  182570  159833  108337  198426  137119  214529  186658
ENSG00000198712  71278   69901   61623   52300   62077   73408   74603   51188
ENSG00000228253   6725    5876    4779    3987    5114    5317    6332    3599
ENSG00000198899  52554   54379   46647   34537   48939   43951   53419   35444
ENSG00000198938  91687   83461   59999   48030   90512   63528  115894   66823
ENSG00000198840  17468   11492   16652    7853   18885   11209   16175   10158
ENSG00000212907  15309   13323   12073    9825   10850   11984   12299    8128
ENSG00000198886 145731  134217  116449   90961  110788  122543  142594   86406
ENSG00000198786  36762   62660   44252   54041   54285   69670   86429   32933
ENSG00000198695    422     436     449     409     293     471     225     194
ENSG00000198727  55111   51569   60164   32987   54159   55068   68905   38815
ENSG00000276256     33      10     100       6      49      25       4      13
ENSG00000278384     62      12       8       2      12      32      30      13
ENSG00000273748     36      15      19      51      56      53      16      70
ENSG00000271254    129      71      84      80     218     137     176     162
ENSG00000276345      1       0       0       0      51      32       1       0
ENSG00000277856     59      24      54      30     440      16     632     177
ENSG00000275063    112      37     484      49     525      11     691     643
ENSG00000277836     13       6       4       1     106      10      60      13
ENSG00000278817      9      10       4      14      21      12      10       5
ENSG00000277196     29      73      23     268      70     309      80      64
                ALF032B ALF037B ⋯ ALF028C ALF035C ALF034A ALF044B ALF023C
ENSG00000279457   53      50    ⋯    5      53      44      46      39
ENSG00000187634  235     336    ⋯  214     582      82     109     293
ENSG00000188976  746    1011    ⋯  781     673     597     761     640
ENSG00000187961  158     279    ⋯  111     148     100     159     113
ENSG00000187583   21      72    ⋯   49      20       6      27      26
ENSG00000188290  101     163    ⋯  176     195     119      97     102
ENSG00000187608  344     353    ⋯  175     750      81     336     209
ENSG00000188157 1677    1985    ⋯ 2542    3122    1979    1777    1464
ENSG00000131591  168     204    ⋯  128     157     143     242     132
ENSG00000162571   21      40    ⋯  171       6       4       6       0
ENSG00000186891   43      43    ⋯   58      18       5      14      26
ENSG00000186827   81      95    ⋯   63     128      53     255      56
ENSG00000078808 1725    2584    ⋯ 1642    2173    1726    1973    1877
ENSG00000176022  200     304    ⋯  243     335     208     259     193
ENSG00000184163   16       8    ⋯    3      20      14      12      10
ENSG00000160087  447     717    ⋯  454     527     436     509     436
ENSG00000162572  130     118    ⋯   61      93      79      35      75
ENSG00000131584 1018    1622    ⋯  700     969     608     884     824
ENSG00000169972  102     129    ⋯  107      83      83     102      78
ENSG00000127054  938    1416    ⋯ 1004     876     968    1059     875
ENSG00000224051  253     304    ⋯  234     289     229     314     153
ENSG00000169962   12      30    ⋯   19       3      13       5      12
ENSG00000107404  610     932    ⋯  630     726     831     791     477
ENSG00000162576 2615    2673    ⋯ 1089    3160    1402    1468    2436
ENSG00000175756  368     571    ⋯  476     455     404     598     335
ENSG00000221978 3394    5355    ⋯ 2479    2670    3050    3346    2935
ENSG00000242485  528     836    ⋯  615     521     558     734     460
ENSG00000235098  150     266    ⋯  411     161     135     216      53
ENSG00000179403  530    1696    ⋯ 1092     757     532     804     929
ENSG00000215915   44      84    ⋯  105      65     111      82      18
⋮               ⋮       ⋮       ⋱ ⋮       ⋮       ⋮       ⋮       ⋮
ENSG00000067646    201     269  ⋯      0       0       0       0     217
ENSG00000114374    662    1193  ⋯      0       0       1       0     786
ENSG00000067048   1058    2196  ⋯      1       0       0       0    1484
ENSG00000183878    305     574  ⋯      0       0       0       0     326
ENSG00000165246     79     206  ⋯      0       0       0       0     185
ENSG00000012817   1565    2537  ⋯      2       0       1       1    1140
ENSG00000198692    224     424  ⋯      0       0       0       0     185
ENSG00000198888  34802   78165  ⋯  44666   74531   44793   65633   27235
ENSG00000198763  31918   85561  ⋯  41150   66935   42246   60068   25700
ENSG00000198804 192021  406674  ⋯ 178904  292888  119888  183226  130583
ENSG00000198712  52281  127483  ⋯  64327  102618   54192   88015   46288
ENSG00000228253   4726   12206  ⋯   5800    8142    4796    8348    3851
ENSG00000198899  36721   99779  ⋯  53217   76138   38078   69571   31769
ENSG00000198938  86800  186271  ⋯  87975  129500   49551  107561   60174
ENSG00000198840  10958   31793  ⋯  15779   21788   13698   16946   10479
ENSG00000212907   7549   27932  ⋯  13481   20898   12915   20188    8958
ENSG00000198886  91501  277525  ⋯ 129728  199708  114119  186027   82032
ENSG00000198786  24512   77442  ⋯  53099   78748   82356   89711   26680
ENSG00000198695    133     625  ⋯    288     624     459    1477     303
ENSG00000198727  45898  123405  ⋯  60931   84955   55342   67812   38964
ENSG00000276256     10      30  ⋯     42      21      25      10      25
ENSG00000278384     21      51  ⋯     17      23       9       4      13
ENSG00000273748     38      70  ⋯     29      70      65      21      33
ENSG00000271254    151     174  ⋯    151     117      91      95      57
ENSG00000276345      0       0  ⋯      0       0       0       0       0
ENSG00000277856     19     118  ⋯     52       6      16       2      75
ENSG00000275063     51     701  ⋯    148       0      16      15     470
ENSG00000277836      9       5  ⋯     56       2       2       0       6
ENSG00000278817     11       6  ⋯     12      11       7       0       4
ENSG00000277196     50      39  ⋯    170     123     156      61      12
                ALF010A ALF027B ALF012B ALF025C ALF032C
ENSG00000279457   16      67      35      49      45
ENSG00000187634   40     271      77      80     122
ENSG00000188976  519     650     826     668     610
ENSG00000187961  115     160     196     140     140
ENSG00000187583    5      57      45       9      47
ENSG00000188290  124     219      78     160     181
ENSG00000187608  338     138    1523     517     166
ENSG00000188157 1046    2769     609    1803    2525
ENSG00000131591  127     200     211     115     180
ENSG00000162571   15     210       5      49     107
ENSG00000186891   13      33     145      13      61
ENSG00000186827   77      42     272      82      52
ENSG00000078808 1601    1508    1623    1452    1493
ENSG00000176022  401     186     425     175     185
ENSG00000184163    5       9       6       5       7
ENSG00000160087  471     407     658     406     361
ENSG00000162572   66      95      58      72     103
ENSG00000131584  670     974     759     709     717
ENSG00000169972   98      96     140      83      94
ENSG00000127054  803    1075    1006     826     888
ENSG00000224051  335     235     276     277     191
ENSG00000169962    7       8       9       5      21
ENSG00000107404  701     619     458     624     608
ENSG00000162576 2036    1697    1011     931    1226
ENSG00000175756  626     323    1066     438     407
ENSG00000221978 2343    3400    2376    2614    2907
ENSG00000242485  570     452     871     568     454
ENSG00000235098  148     473     174     228     458
ENSG00000179403  509     890     665     574    1050
ENSG00000215915   75      72     121      80      47
⋮               ⋮       ⋮       ⋮       ⋮       ⋮
ENSG00000067646    131     196       0     268     209
ENSG00000114374    438     855       1     731     962
ENSG00000067048    877    1307       1    1366    1598
ENSG00000183878    212     375       0     320     351
ENSG00000165246     37     174       0      41     170
ENSG00000012817    773    1407       1    1209    1282
ENSG00000198692    219     223       0     274     261
ENSG00000198888 120904   69050  136776   73674   43259
ENSG00000198763 138726   66654  145794   89208   39121
ENSG00000198804 393852  290486  493411  324024  189745
ENSG00000198712 172162   96755  221446  124120   56892
ENSG00000228253  13011    7746   11860    7757    4890
ENSG00000198899 125935   85626  144247   84453   44471
ENSG00000198938 188589  154684  277066  130166   92398
ENSG00000198840  50231   31207   40323   30389   16231
ENSG00000212907  33266   19451   33515   20722   11838
ENSG00000198886 333687  216624  413189  229291  112028
ENSG00000198786 203261   48440  140963   61049   52985
ENSG00000198695   1811     418    2269     470     339
ENSG00000198727 179990  106858  155899  102581   51558
ENSG00000276256     22      54      68      22       6
ENSG00000278384      6      56       1      19      24
ENSG00000273748     15      50      12      34      62
ENSG00000271254     73     149      41     136     109
ENSG00000276345      0      20       0       0       0
ENSG00000277856     13      55      23       6       7
ENSG00000275063     50     123      25      34      93
ENSG00000277836      1      49       4       0      16
ENSG00000278817     31      12      15      10      11
ENSG00000277196    278     126      40     100      96

In [14]:
# save metadata and filtered counts for DGE and downstream analysis
#fwrite(counts, row.names=TRUE, "GSE213001_filtered_counts.txt")
#fwrite(metaclean, row.names=TRUE, "GSE213001_filtered_metadata.txt")